if &compatible
    set compatible
endif

set runtimepath+=~/.vim/dein/repos/github.com/Shougo/dein.vim
function! s:source_rc(path)
    let abspath = resolve(expand('~/.vim/rc/' . a:path))
    execute 'source' abspath
endfunction

let s:dein_dir = expand('~/.vim/dein')
if dein#load_state(s:dein_dir)
    let s:toml = expand('~/.vim/rc/dein.toml')
    let s:toml_lazy = expand('~/.vim/rc/dein_lazy.toml')
    call dein#begin(s:dein_dir)
    call dein#load_toml(s:toml)
    call dein#load_toml(s:toml_lazy)
    call dein#end()
endif

let g:vimproc#download_windows_dll = 1
if dein#check_install(['vimproc'])
    call dein#install(['vimproc'])
endif

if dein#check_install()
    call dein#install()
endif

syntax enable
filetype plugin indent on

call s:source_rc('encodings.rc.vim')
call s:source_rc('options.rc.vim')
call s:source_rc('mappings.rc.vim')
call s:source_rc('filetypes.rc.vim')

if has('win32') || has('win64')
    call s:source_rc('windows.rc.vim')
else
    call s:source_rc('unix.rc.vim')
endif

if has('gui_running')
    call s:source_rc('gui.rc.vim')
endif

set runtimepath+=~/.vim/rc/
runtime! plugins/*.vim
