if &compatible
    set compatible
endif

function! s:source_rc(path)
    let abspath = resolve(expand('~/.vim/rc/' . a:path))
    execute 'source' abspath
endfunction


call s:source_rc('encodings.rc.vim')
call s:source_rc('options.rc.vim')
call s:source_rc('mappings.rc.vim')

if has('win32') || has('win64')
    call s:source_rc('windows.rc.vim')
else
    call s:source_rc('unix.rc.vim')
endif

if has('gui_running')
    call s:sourcerc('gui.rc.vim')
endif
