[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'fatih/vim-go'
on_ft = 'go'
hook_post_update = '''
    execute ':GoInstallBinaries'
'''
hook_source = '''
    let g:go_def_mapping_enabled = 0
    let g:go_doc_keywordprg_enabled = 0
    let g:go_list_type="quickfix"
    let g:go_fmt_command="goimports"
    let g:go_highlight_types=1
    let g:go_highlight_fields=1
    let g:go_highlight_functions=1
    let g:go_highlight_function_calls=1
    let g:go_fmt_fail_silently=1
'''

[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = ['javascript', 'typescript', 'javascriptreact', 'typescript.tsx']

[[plugins]]
repo = 'HerringtonDarkholme/yats.vim'
on_ft = ['javascript', 'typescript', 'javascriptreact', 'typescript.tsx']

[[plugins]]
repo = 'maxmellon/vim-jsx-pretty'
on_ft = ['javascript', 'typescript', 'javascriptreact', 'typescript.tsx']

[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = 'markdown'

