[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'junegunn/fzf.vim'
hook_add = '''
    source $XDG_CONFIG_HOME/nvim/plugins/fzf.vim
'''

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
    source $XDG_CONFIG_HOME/nvim/plugins/lightline.rc.vim
'''

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'tyru/open-browser.vim'

[[plugins]]
repo = 'terryma/vim-expand-region'

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'joshdick/onedark.vim'

[[plugins]]
repo = 'lifepillar/vim-solarized8'

[[plugins]]
repo = 'morhetz/gruvbox'

[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'
merge = 0
hook_add = '''
    source $XDG_CONFIG_HOME/nvim/plugins/coc.vim
'''

