[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = '''
    source $XDG_CONFIG_HOME/nvim/rc/plugins/denite.vim
'''

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'Shougo/neoyank.vim'

[[plugins]]
repo = 'Shougo/unite-outline'

[[plugins]]
repo = 'Shougo/defx.nvim'
hook_add = '''
    source $XDG_CONFIG_HOME/nvim/rc/plugins/defx.vim
'''

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
    source $XDG_CONFIG_HOME/nvim/rc/plugins/lightline.rc.vim
'''

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'tyru/open-browser.vim'

[[plugins]]
repo = 'terryma/vim-expand-region'

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'altercation/vim-colors-solarized'

[[plugins]]
repo = 'joshdick/onedark.vim'

[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'
merge = 0
hook_add = '''
    source $XDG_CONFIG_HOME/nvim/rc/plugins/coc.vim
'''

